### ISSUE TITLE
Problem displaying day of week

### ISSUE THREAD

**Issue by cvarino** [myneur/late#1]
Hi,

There is a problem when the day of week is displayed on Spanish, at least on forerunner 735xt (7.20)
It is: "Mié 3" is displayed as "Mi□ 3".
Maybe a possible easy solution is "Mie 3"

BR

**Comment by weechatter** [comment]
looks like an utf-8 decoding problem.

**Comment by myneur** [comment]
It was a font problem. I embedded a special characters in the font.
