### ISSUE TITLE
Simple weather sunny/rainy

### ISSUE THREAD

**Issue by myneur** [myneur/late#23]
![](https://productboard-files.s3.amazonaws.com/production/attachments/4e9512d8ae0a3c222a9a9a48a8b09eba935d84199ef70db52e5c66e62a15e9b9/weather.png)

Show simple weather forecast from yr.on API. 

- rain in blue

- sun in yellow

- snow white

- darker colors during night

# [Delivery](https://app.asana.com/0/1198503024526957/board)

**Comment by myneur** [comment]
Link to feature: https://myneur.productboard.com/feature-board/planning/features/3220407

**Comment by idoo** [comment]
awesome idea!

**Comment by myneur** [comment]
tested in weather branch, but current weather data is too big that it runs out of memory. Waiting for a reply from yr.no and darksky.net if it is possible to limit columns/values in response.

**Comment by idoo** [comment]
@myneur as a temporary solution we could use heroku middleware to reduce amount of data
or maybe http://openweathermap.org

**Comment by myneur** [comment]
@idoo don't you want to join us and contribute? 
It could be just limiting 
https://api.darksky.net/forecast/<API_KEY>/<lat>,<lon>?exclude=currently,minutely,daily,flags,alerts&units=ca
only to next fields: 
https://github.com/myneur/late/blob/weather/data-test/darksky23h1.json
Those are enough and do not run out of memory. But I don't see a way how to do it just by API parameters. 
Yr.no is the most accurate, but they have even more verbose XML API. Darksky seems to bee also good.
I don't know about the accuracy of openweather.org though.

**Comment by DenizUgur** [comment]
Hi @myneur, long time 😄 I can create that middleware. I also recommend you to check out clearoutside.com for well clear skies. It could be a nice feature.

In my opinion, this watch face is still the best one on the market and it could be better with your ideas.
