### ISSUE TITLE
Oauth streamline (device)

### ISSUE THREAD

**Issue by myneur** [myneur/late#33]
> Google blocks Garmin browser and none of them is willing to fix it. 

> The only workaround we found is making user to open oauth in his mobile browser and paste the auth code back. Dirty but works. Or we might be able to use OAuth for devices

# OAuth for devices can do the trick <https://developers.google.com/identity/protocols/OAuth2ForDevices>

1. show link + code on watch

2. prompt with auth page that will direct him to the link in an easier way

3. he logs-in there

![](https://productboard-files.s3.amazonaws.com/production/attachments/53354d2d6d8cea895d4aa2245eef7466fcae9b8660736cf8cf13a7928d1e089a/watch-prompt.png)

<p></p>

**Comment by myneur** [comment]
Link to feature: https://myneur.productboard.com/feature-board/planning/features/3369881

**Comment by myneur** [comment]
@DenizUgur here's the prototype how the OAuth for devices prototype could work: https://invis.io/NSV2EKKAYG8#/395765456_01-Watch-Prompt

Surely, let's test first if the OAuth for devices would work even without selecting the calendars. 

Then we can continue. Because the oauth must be in browser because of the Garmin being blocked by Google, the calendar configuration would have to be done back in Garmin Mobile once the watch loads the calendars. It might be done by second makeOAuthRequest while keeping the watch actually authenticated. Only the calendar indexes and colors would be saved. If not possible, that would have to be done in the watch or we would have to find a different way. The colors could match the watch colors. 
Let's prove if this works even without the styles when you'll have time and if it will work I can ask some web developers if they don't want to join and do CSS. 
Let's try if we can get close into such onboarding:) Thanks:)

**Comment by myneur** [comment]
Works except for some devices where manifests a bug that waits for Garmin to fix: https://forums.garmin.com/developer/connect-iq/i/bug-reports/makewebrequest-bad-request-on-some-devices
Vote there if it manifests on your device.

**Comment by DenizUgur** [comment]
Done. It's weird that they still haven't solved this issue.
