### ISSUE TITLE
Noon on top and midnight at the bottom

### ISSUE THREAD

**Issue by Reedyn** [myneur/late#43]
Hi. I'm wondering if it would be possible to add a setting to adjust the outer 24 hour circle 180 degrees so that noon is on top and midnight is on the bottom. For me (and I guess many others) having it this way feels more familiar.

Great app!

**Comment by myneur** [comment]
Hi Reedyn, there is surely an infinite number of variations that many people would like or prefer, but implementing all of them is against our goals to keep the app simple.
For that reason I'm closing this request as we decided not to implement this one. 
For those for whom it might be so valuable that they want to invest their time into develop and maintain it, the code here is up to date and available for them.
