### ISSUE TITLE
Epix Pro models are not supported

### ISSUE THREAD

**Issue by tvelocity** [myneur/late#44]
Hello,

Currently the watch faces support non-pro Fenix 7 and Epix models, and the Fenix 7 Pro variants (all sizes), according to [Connect IQ](https://apps.garmin.com/en-US/apps/e767e34d-7b85-4c44-bf4f-19afeb71a5db#compatible-devices), and the project's source code.

However, the watch faces are not available for the Epix Pro variants. Is there a particular reason why these models cannot be supported?

**Comment by myneur** [comment]
Hi, the only reason is that it requires more work to add the support for them after Garmin did changes in their latest framework and those watches are not supported by the older framework. It's planned, but it will take a while.

**Comment by myneur** [comment]
Hi, we added support for the Fenix 7 and Epix Pro devices.
You can [download the simply late! watch face from the store now](https://apps.garmin.com/en-US/apps/3532114a-c93c-447a-bc8e-25999ea599fc).
Best! 
simply late!

**Comment by tvelocity** [comment]
Omg thank you so much! This is a really welcome Christmas surprise, this watch face really helps me to better know how much time I have during the day and I can finally use it on my newer watch 😄

**Comment by tvelocity** [comment]
Also I can confirm everything works perfectly on the Epic Pro 44mm. I tried both the late and analogue variants, with google calendar (6 calendars) and weather integration, every feature I tried works flawlessly and it looks really good on the OLED screen.

I have found no other watch face that matches this one in usefulness, a very amazing job 👍👍👍
